/**
 * Rust -> TypeScript response contract.
 *
 * `tests/fixtures/responses/*.json` are generated by
 * `src-tauri/tests/response_fixtures.rs` from the real Rust response structs
 * (serde output, compared byte-for-byte by `cargo test`). This file pins the
 * TypeScript response types in `src/lib/api/` to those files:
 *
 * - compile time (`pnpm check`): every TS field must exist in the fixture with
 *   a compatible primitive, and every fixture field must exist on the TS type.
 *   A rename or a dropped field on either side fails svelte-check.
 * - run time (`pnpm test`): enum-valued fields must hold a member of the TS
 *   string union, so a new Rust variant that reaches a fixture fails Vitest.
 *
 * A JSON import is typed with widened literals (`"ready"` is just `string`),
 * which is why unions are pinned at run time instead of by `satisfies` alone.
 */
import { describe, expect, it } from 'vitest';

import type { Account, AccountKind } from './accounts';
import type { BackupFileResult, ImportResult } from './backup';
import type { BalanceList } from './balances';
import type { BootStatus, RecoveryReason } from './boot';
import type { BudgetStatus } from './budgets';
import type { Category, CategoryType } from './categories';
import type { AppInfo } from './index';
import type {
  CategoryReport,
  MonthlyBucket,
  MonthlyReport,
  MonthlySummary,
  NetWorthReport,
  YearlyReport,
} from './reports';
import type {
  ExpansionResult,
  Frequency,
  OccurrencePreview,
  RecurringRuleView,
  SkipReason,
} from './recurring';
import type { ListTransactionResult, TxType } from './transactions';

import appError from '../../../tests/fixtures/responses/app_error.json';
import appInfo from '../../../tests/fixtures/responses/app_info.json';
import bootStatusReady from '../../../tests/fixtures/responses/boot_status.ready.json';
import bootStatusRecovery from '../../../tests/fixtures/responses/boot_status.recovery.json';
import expandDueRecurring from '../../../tests/fixtures/responses/expand_due_recurring.json';
import exportBackupToFile from '../../../tests/fixtures/responses/export_backup_to_file.json';
import importJson from '../../../tests/fixtures/responses/import_json.json';
import listAccounts from '../../../tests/fixtures/responses/list_accounts.json';
import listBalances from '../../../tests/fixtures/responses/list_balances.json';
import listBudgetStatuses from '../../../tests/fixtures/responses/list_budget_statuses.json';
import listCategories from '../../../tests/fixtures/responses/list_categories.json';
import listRecurringRules from '../../../tests/fixtures/responses/list_recurring_rules.json';
import listTopBudgetStatuses from '../../../tests/fixtures/responses/list_top_budget_statuses.json';
import listTransactions from '../../../tests/fixtures/responses/list_transactions.json';
import monthlySeries from '../../../tests/fixtures/responses/monthly_series.json';
import monthlySummary from '../../../tests/fixtures/responses/monthly_summary.json';
import previewRecurringOccurrences from '../../../tests/fixtures/responses/preview_recurring_occurrences.json';
import reportByCategory from '../../../tests/fixtures/responses/report_by_category.json';
import reportMonthly from '../../../tests/fixtures/responses/report_monthly.json';
import reportNetWorthSeries from '../../../tests/fixtures/responses/report_net_worth_series.json';
import reportYearly from '../../../tests/fixtures/responses/report_yearly.json';

// ---------------------------------------------------------------------------
// Compile-time helpers (no runtime effect)
// ---------------------------------------------------------------------------

/** The response type as a JSON import infers it: literal unions widened to their primitive. */
type Wire<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T extends readonly (infer U)[]
        ? Wire<U>[]
        : T extends object
          ? { [K in keyof T]: Wire<T[K]> }
          : T;

/** Key skeleton of `T`: same nesting, every leaf (including `null`) is `unknown`. */
type Shape<T> = [T] extends [never]
  ? unknown
  : T extends readonly (infer U)[]
    ? Shape<U>[]
    : T extends object
      ? { [K in keyof T]-?: Shape<NonNullable<T[K]>> }
      : unknown;

/**
 * Fixture -> type. Fails when the TS type has a field the fixture lacks
 * (Rust renamed it and the fixture was regenerated) or a primitive differs.
 */
function fixtureFits<T>(_fixture: Wire<T>): void {}

/**
 * Type -> fixture. Fails when the fixture has a field the TS type lacks
 * (the TS type dropped or renamed it). Use with `shapeOf<ResponseType>()`.
 */
function typeCovers<F>(_skeleton: Shape<F>): void {}

function shapeOf<T>(): Shape<T> {
  return undefined as unknown as Shape<T>;
}

/** Every member of the string union `T`; the `Record` keeps the list exhaustive at compile time. */
function members<T extends string>(all: Record<T, true>): readonly string[] {
  return Object.keys(all);
}

// ---------------------------------------------------------------------------
// Wire enum values (snake_case on the wire, see response_fixtures.rs)
// ---------------------------------------------------------------------------

const BOOT_STATES = members<BootStatus['state']>({ ready: true, recovery: true });
const RECOVERY_REASONS = members<RecoveryReason>({
  key_missing: true,
  decrypt_failed: true,
  key_corrupt: true,
  keychain_error: true,
});
const ACCOUNT_KINDS = members<AccountKind>({
  cash: true,
  bank: true,
  credit_card: true,
  e_money: true,
  investment: true,
});
const CATEGORY_TYPES = members<CategoryType>({ income: true, expense: true });
const TX_TYPES = members<TxType>({ income: true, expense: true, transfer: true });
const FREQUENCIES = members<Frequency>({ monthly: true, weekly: true, yearly: true });
const SKIP_REASONS = members<SkipReason>({
  archived_account: true,
  archived_counter_account: true,
  archived_category: true,
  category_type_mismatch: true,
  malformed_rule: true,
});

/** Fixture files asserted below; the last test checks nothing on disk is missing here. */
const COVERED_FIXTURES = [
  'app_error.json',
  'app_info.json',
  'boot_status.ready.json',
  'boot_status.recovery.json',
  'expand_due_recurring.json',
  'export_backup_to_file.json',
  'import_json.json',
  'list_accounts.json',
  'list_balances.json',
  'list_budget_statuses.json',
  'list_categories.json',
  'list_recurring_rules.json',
  'list_top_budget_statuses.json',
  'list_transactions.json',
  'monthly_series.json',
  'monthly_summary.json',
  'preview_recurring_occurrences.json',
  'report_by_category.json',
  'report_monthly.json',
  'report_net_worth_series.json',
  'report_yearly.json',
];

describe('Rust response fixtures match the TypeScript API types', () => {
  it('boot_status (ready) is a BootStatus', () => {
    fixtureFits<BootStatus>(bootStatusReady);
    typeCovers<typeof bootStatusReady>(shapeOf<BootStatus>());

    expect(BOOT_STATES).toContain(bootStatusReady.state);
    expect(bootStatusReady.recovery_reason).toBeNull();
  });

  it('boot_status (recovery) is a BootStatus with a known recovery_reason', () => {
    fixtureFits<BootStatus>(bootStatusRecovery);
    typeCovers<typeof bootStatusRecovery>(shapeOf<BootStatus>());

    expect(BOOT_STATES).toContain(bootStatusRecovery.state);
    expect(RECOVERY_REASONS).toContain(bootStatusRecovery.recovery_reason);
  });

  it('app_info is an AppInfo', () => {
    fixtureFits<AppInfo>(appInfo);
    typeCovers<typeof appInfo>(shapeOf<AppInfo>());
  });

  it('list_balances is a BalanceList', () => {
    fixtureFits<BalanceList>(listBalances);
    typeCovers<typeof listBalances>(shapeOf<BalanceList>());

    expect(listBalances.accounts.length).toBeGreaterThan(0);
    for (const account of listBalances.accounts) {
      expect(ACCOUNT_KINDS).toContain(account.kind);
    }
  });

  it('monthly_summary is a MonthlySummary', () => {
    fixtureFits<MonthlySummary>(monthlySummary);
    typeCovers<typeof monthlySummary>(shapeOf<MonthlySummary>());

    expect(monthlySummary.by_category.length).toBeGreaterThan(0);
    for (const aggregate of monthlySummary.by_category) {
      expect(CATEGORY_TYPES).toContain(aggregate.type);
    }
  });

  it('monthly_series is a MonthlyBucket[]', () => {
    fixtureFits<MonthlyBucket[]>(monthlySeries);
    typeCovers<typeof monthlySeries>(shapeOf<MonthlyBucket[]>());

    expect(monthlySeries.length).toBeGreaterThan(0);
  });

  it('report_monthly is a MonthlyReport', () => {
    fixtureFits<MonthlyReport>(reportMonthly);
    typeCovers<typeof reportMonthly>(shapeOf<MonthlyReport>());

    // 比較対象が 0 のとき割合は null になる（0 除算をフロントに出さない）。
    expect(reportMonthly.yoy.expense_percent).toBeNull();
    for (const aggregate of [...reportMonthly.top_expense, ...reportMonthly.top_income]) {
      expect(CATEGORY_TYPES).toContain(aggregate.type);
    }
  });

  it('report_yearly is a YearlyReport with twelve months', () => {
    fixtureFits<YearlyReport>(reportYearly);
    typeCovers<typeof reportYearly>(shapeOf<YearlyReport>());

    expect(reportYearly.months).toHaveLength(12);
  });

  it('report_by_category is a CategoryReport whose series match the month axis', () => {
    fixtureFits<CategoryReport>(reportByCategory);
    typeCovers<typeof reportByCategory>(shapeOf<CategoryReport>());

    for (const series of reportByCategory.series) {
      expect(CATEGORY_TYPES).toContain(series.type);
      expect(series.points).toHaveLength(reportByCategory.months.length);
    }
  });

  it('report_net_worth_series is a NetWorthReport with an empty average head', () => {
    fixtureFits<NetWorthReport>(reportNetWorthSeries);
    typeCovers<typeof reportNetWorthSeries>(shapeOf<NetWorthReport>());

    // 窓が埋まる 3 点目まで移動平均は出ない。
    expect(reportNetWorthSeries.points[0].net_moving_avg).toBeNull();
    expect(reportNetWorthSeries.points[2].net_moving_avg).not.toBeNull();
  });

  it('list_transactions is a ListTransactionResult', () => {
    fixtureFits<ListTransactionResult>(listTransactions);
    typeCovers<typeof listTransactions>(shapeOf<ListTransactionResult>());

    expect(listTransactions.items.length).toBeGreaterThan(0);
    for (const transaction of listTransactions.items) {
      expect(TX_TYPES).toContain(transaction.type);
    }
  });

  it('list_categories is a Category[]', () => {
    fixtureFits<Category[]>(listCategories);
    typeCovers<typeof listCategories>(shapeOf<Category[]>());

    expect(listCategories.length).toBeGreaterThan(0);
    for (const category of listCategories) {
      expect(CATEGORY_TYPES).toContain(category.type);
    }
  });

  it('list_accounts is an Account[]', () => {
    fixtureFits<Account[]>(listAccounts);
    typeCovers<typeof listAccounts>(shapeOf<Account[]>());

    expect(listAccounts.length).toBeGreaterThan(0);
    for (const account of listAccounts) {
      expect(ACCOUNT_KINDS).toContain(account.kind);
    }
  });

  it('list_budget_statuses is a BudgetStatus[]', () => {
    fixtureFits<BudgetStatus[]>(listBudgetStatuses);
    typeCovers<typeof listBudgetStatuses>(shapeOf<BudgetStatus[]>());

    expect(listBudgetStatuses.length).toBeGreaterThan(0);
  });

  it('list_top_budget_statuses is a BudgetStatus[]', () => {
    fixtureFits<BudgetStatus[]>(listTopBudgetStatuses);
    typeCovers<typeof listTopBudgetStatuses>(shapeOf<BudgetStatus[]>());

    expect(listTopBudgetStatuses.length).toBeGreaterThan(0);
  });

  it('import_json is an ImportResult', () => {
    fixtureFits<ImportResult>(importJson);
    typeCovers<typeof importJson>(shapeOf<ImportResult>());

    expect(importJson.warnings.length).toBeGreaterThan(0);
  });

  it('export_backup_to_file (Some) is a BackupFileResult', () => {
    // The cancelled case is a bare `null`, which needs no fixture.
    fixtureFits<BackupFileResult>(exportBackupToFile);
    typeCovers<typeof exportBackupToFile>(shapeOf<BackupFileResult>());
  });

  it('app_error is a bare string (AppError serializes to its message)', () => {
    fixtureFits<string>(appError);

    expect(typeof appError).toBe('string');
    expect(appError.length).toBeGreaterThan(0);
  });

  it('list_recurring_rules is a RecurringRuleView[]', () => {
    fixtureFits<RecurringRuleView[]>(listRecurringRules);
    typeCovers<typeof listRecurringRules>(shapeOf<RecurringRuleView[]>());

    for (const view of listRecurringRules) {
      expect(TX_TYPES).toContain(view.rule.type);
      expect(FREQUENCIES).toContain(view.rule.frequency);
    }
    // 停止中の振替ルールを 1 件含む: counter_account_id あり / category_id なし。
    expect(listRecurringRules.some((v) => v.rule.counter_account_id !== null)).toBe(true);
    expect(listRecurringRules.some((v) => v.next_occurrence === null)).toBe(true);
  });

  it('expand_due_recurring is an ExpansionResult with a known skip reason', () => {
    fixtureFits<ExpansionResult>(expandDueRecurring);
    typeCovers<typeof expandDueRecurring>(shapeOf<ExpansionResult>());

    for (const skipped of expandDueRecurring.skipped) {
      expect(SKIP_REASONS).toContain(skipped.reason);
    }
  });

  it('preview_recurring_occurrences is an OccurrencePreview', () => {
    fixtureFits<OccurrencePreview>(previewRecurringOccurrences);
    typeCovers<typeof previewRecurringOccurrences>(shapeOf<OccurrencePreview>());
  });

  it('asserts every fixture file on disk', () => {
    const onDisk = Object.keys(import.meta.glob('../../../tests/fixtures/responses/*.json'))
      .map((path) => path.slice(path.lastIndexOf('/') + 1))
      .sort();

    expect(onDisk).toEqual([...COVERED_FIXTURES].sort());
  });
});
